#!/bin/bash

PWD="$(pwd)"
SCRIPT="$(readlink -f $0)"
SCRIPTPATH="$(dirname ${SCRIPT})"
FUNCTIONPATH="${SCRIPTPATH}/functions"
CONFIG_DIR="$HOME/.wifi-crack"
CONFIG_FILE="$CONFIG_DIR/config.conf"
source "$CONFIG_FILE"

source "$CONFIG_INTERFACE"
source "$CURRENT_ATTACK_FILE"
source "$CONFIG_ATTACK"

#### VARIAVEIS UTILIZADAS
# DATA
# DIR_CONFIG_USER
# INTERFACE
# INTERFACE_MAC
# INTERFACE_INTERNET
# VITIMA
# CHANNEL
# BSSID
# STATION
# DHCP_RANGE
# DHCP_SERVER
# DHCP_RANGE_START
# DHCP_RANGE_END

